* Git for course deployment (Fall 2019)
** Introductions (5 min)

   everyone introduces themselves, just says what there teaching
   and research interests are, and their background with git and/or
   website development.

   present some data from survey, and pair up people into
   experience-inexperienced pairs (preferably matched with same
   text editor/os).

** Introduce git and github (5 min)

   Present learning objectives and introduce git and github.

** split off and install git (10 min)

   Then split off and have everyone install git, make sure it is
   working, sign up for github, and clone the course repository.

   Lots of this will be done with pairs, but we can bring back into
   discussions at table and with the whole group depending on how
   much trouble people have (hopefully it goes smooth and no need
   to have a lot of discussion).

   tell students to take notes on anything that was confusing (we
   will use this later)

   https://guides.github.com/activities/hello-world/

** Present github features (5 min)
   pull requests, issues.

** discuss github features (10 min)

   have a think-pair-share about how these github features can be
   used in a course setting, even though they were developed
   primarily for software development.

** interactive activity  (15 min)

   tell students to work in pairs in order to either change the
   course materials, or open an issue with their comments.
