* Using pandoc to generate course materials
** merge group changes to improve website (10 min)

   come together as a group, and I will work though on the
   projector merging everyone's changes. I will take guidance from
   ppl on what to do so it is a group activity.

   could maybe do one more iteration where we let students respond
   to comments or update pull requests.

** explain pandoc, run through improved website (10 min)

   If I had them make changes to markdown or org mode files, then
   this would be the time to also show how I use pandoc or whatever
   tool to generate the website from the markdown and/or org mode
   files. Also introduce makefiles here I guess - maybe not. No make
   for windows.

   pandoc intro:

   https://pandoc.org/getting-started.html

   try it online:

   https://pandoc.org/try/

** debrief, feedback, other tools (10-20 min)

   Time permitting discuss pandoc in more detail, discuss gitlab vs
   github vs bitbucket, talk about juptyer notebooks and nbgrader
   and automated submissions.

   solicit feedback on benefits vs downsides (need to pick single
   markdown format in order to avoid circular dependencies in
   makefile?).

** timing
   right now time is a little high, 1 hr 20 - 1 hr 30 min. Should
   do run through with Chloe and see how things go.
