* Git for course deployment plan (Fall 2019)
** Introductions (5 min)

   everyone introduces themselves, just says what there teaching
   and research interests are, and their background with git and/or
   website development.

   present some data from survey, and pair up people into
   experience-inexperienced pairs (preferably matched with same
   text editor/os).

** Introduce git and github (5 min)

   Present learning objectives and introduce git and github.

** split off and install git (10 min)
   Then split off and have everyone install git, make sure it is
   working, sign up for github, and clone the course repository.

   Lots of this will be done with pairs, but we can bring back into
   discussions at table and with the whole group depending on how
   much trouble people have (hopefully it goes smooth and no need
   to have a lot of discussion).

   tell students to take notes on anything that was confusing (we
   will use this later)

** Present github features (5 min)
   pull requests, issues.

** discuss github features (10 min)
   have a think-pair-share about how these github features can be
   used in a course setting, even though they were developed
   primarily for software development.

** interactive activity  (15 min)

   tell students to work in pairs in order to either change the
   course materials, or open an issue with their comments.

** merge group changes to improve website (10 min)

   come together as a group, and I will work though on the
   projector merging everyone's changes. I will take guidance from
   ppl on what to do so it is a group activity.

   could maybe do one more iteration where we let students respond
   to comments or update pull requests.

** explain pandoc, run through improved website (10 min)

   If I had them make changes to markdown or org mode files, then
   this would be the time to also show how I use pandoc or whatever
   tool to generate the website from the markdown and/or org mode
   files. Also introduce makefiles here I guess.

** debrief, feedback, other tools (10-20 min)

   Time permitting discuss pandoc in more detail, discuss gitlab vs
   github vs bitbucket, talk about juptyer notebooks and nbgrader
   and automated submissions.

   solicit feedback on benefits vs downsides (need to pick single
   markdown format in order to avoid circular dependencies in
   makefile?).

** timing
   right now time is a little high, 1 hr 20 - 1 hr 30 min. Should
   do run through with Chloe and see how things go.
